// Date: 17/05/2014 10:03:33 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package projecte.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCondensor extends ModelBase
{
  //fields
	public ModelRenderer Base;
    public ModelRenderer Latch;
    public ModelRenderer TopRight;
    public ModelRenderer TopLeft;
  
  public ModelCondensor()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(0F, 0F, 0F, 14, 10, 14);
      Base.setRotationPoint(-7F, 14F, -7F);
      Base.setTextureSize(64, 64);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Latch = new ModelRenderer(this, 0, 0);
      Latch.addBox(5F, -6F, 6F, 4, 1, 2);
      Latch.setRotationPoint(-7F, 15F, -7F);
      Latch.setTextureSize(64, 64);
      Latch.mirror = true;
      setRotation(Latch, 0F, 0F, 0F);
      TopRight = new ModelRenderer(this, 0, 44);
      TopRight.addBox(-7F, -5F, 0F, 7, 5, 14);
      TopRight.setRotationPoint(7F, 15F, -7F);
      TopRight.setTextureSize(64, 64);
      TopRight.mirror = true;
      setRotation(TopRight, 0F, 0F, 0F);
      TopLeft = new ModelRenderer(this, 0, 25);
      TopLeft.addBox(0F, -5F, 0F, 7, 5, 14);
      TopLeft.setRotationPoint(-7F, 15F, -7F);
      TopLeft.setTextureSize(64, 64);
      TopLeft.mirror = true;
      setRotation(TopLeft, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    Base.render(f5);
    Latch.render(f5);
    TopRight.render(f5);
    TopLeft.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,entity);
  }
  
  public void renderAll() {
		this.Latch.rotateAngleY = this.TopLeft.rotateAngleY;
		this.TopLeft.render(0.0625F);
		this.Latch.render(0.0625F);
		this.Base.render(0.0625F);
		this.TopRight.render(0.0625F);
		//this.chestBelow.render(0.0625F);
	}


}
