// Date: 13/06/2014 12:47:55 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package projecte.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPipe extends ModelBase {
	// fields
	public ModelRenderer east;
	public ModelRenderer west;
	public ModelRenderer south;
	public ModelRenderer north;
	public ModelRenderer down;
	public ModelRenderer up;
	public ModelRenderer base;
	public ModelRenderer connect1;
	public ModelRenderer connect2;

	public ModelPipe() {
		textureWidth = 64;
		textureHeight = 64;

		east = new ModelRenderer(this, 0, 10);
		east.addBox(0F, 0F, 0F, 7, 2, 2);
		east.setRotationPoint(1F, 15F, -1F);
		east.setTextureSize(64, 64);
		east.mirror = true;
		setRotation(east, 0F, 0F, 0F);
		west = new ModelRenderer(this, 19, 10);
		west.addBox(0F, 0F, 0F, 7, 2, 2);
		west.setRotationPoint(-8F, 15F, -1F);
		west.setTextureSize(64, 64);
		west.mirror = true;
		setRotation(west, 0F, 0F, 0F);
		south = new ModelRenderer(this, 19, 0);
		south.addBox(0F, 0F, 0F, 2, 2, 7);
		south.setRotationPoint(-1F, 15F, -8F);
		south.setTextureSize(64, 64);
		south.mirror = true;
		setRotation(south, 0F, 0F, 0F);
		north = new ModelRenderer(this, 0, 0);
		north.addBox(0F, 0F, 0F, 2, 2, 7);
		north.setRotationPoint(-1F, 15F, 1F);
		north.setTextureSize(64, 64);
		north.mirror = true;
		setRotation(north, 0F, 0F, 0F);
		down = new ModelRenderer(this, 47, 0);
		down.addBox(0F, 0F, 0F, 2, 7, 2);
		down.setRotationPoint(-1F, 17F, -1F);
		down.setTextureSize(64, 64);
		down.mirror = true;
		setRotation(down, 0F, 0F, 0F);
		up = new ModelRenderer(this, 38, 0);
		up.addBox(0F, 0F, 0F, 2, 7, 2);
		up.setRotationPoint(-1F, 8F, -1F);
		up.setTextureSize(64, 64);
		up.mirror = true;
		setRotation(up, 0F, 0F, 0F);
		base = new ModelRenderer(this, 0, 15);
		base.addBox(0F, 0F, 0F, 3, 3, 3);
		base.setRotationPoint(-1.5F, 14.5F, -1.5F);
		base.setTextureSize(64, 64);
		base.mirror = true;
		setRotation(base, 0F, 0F, 0F);
		connect1 = new ModelRenderer(this, 0, 22);
		connect1.addBox(-3F, 7F, -3F, 6, 1, 6);
		connect1.setRotationPoint(0F, 16F, 0F);
		connect1.setTextureSize(64, 64);
		connect1.mirror = true;
		setRotation(connect1, 0F, 0F, 0F);
		connect2 = new ModelRenderer(this, 0, 30);
		connect2.addBox(-2F, 6F, -2F, 4, 1, 4);
		connect2.setRotationPoint(0F, 16F, 0F);
		connect2.setTextureSize(64, 64);
		connect2.mirror = true;
		setRotation(connect2, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		east.render(f5);
		west.render(f5);
		south.render(f5);
		north.render(f5);
		down.render(f5);
		up.render(f5);
		base.render(f5);
		connect1.render(f5);
		connect2.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}
	
	public void renderAll(){
		east.render(0.625f);
		west.render(0.625f);
		south.render(0.625f);
		north.render(0.625f);
		up.render(0.625f);
		down.render(0.625f);
		base.render(0.625f);
//		connect1.render(0.625f);
//		connect2.render(0.625f);

	}
	
	

}
